### ISSUE TITLE
Incorrect dildo mapping

### ISSUE THREAD

**Issue by s4m1r0d4** [AngelBrambila91/Ago-Dic2023Blazor8D1#1]
In `LasPollasHermanas.Server/Program.cs:90: `
`
.SetProperty(dildo => dildo.Material, updatedDildo.Color)
`

Inside the `PUT/dildos/{id}` endpoint. Dildo's material is mapped to the `updatedDildo.Color` instead of the `updatedDildo.Material`

**Comment by AngelBrambila91** [comment]
fixed on commit a82f73b6d14db796ce450468845f046791322781
